name: NASA Automation Tests

on:
  push:
    branches: [ main, development-branch ]
  pull_request:
    branches: [ main, development-branch ]

jobs:
  api-tests:
    name: Run API Tests (@api)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      - name: Run SpecFlow API tests
        run: >
          dotnet test --configuration Release
          --filter "TestCategory=api"
          --no-build
          --logger "trx;LogFileName=api_results.trx"
          --results-directory ./AllureResults
        env:
          HEADLESS: true
          ALLURE_SUITE: "API Tests"
          ALLURE_EPIC: "NASA DONKI API"

      - name: Upload partial Allure results (API)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: AllureResults-API
          path: ./AllureResults

  ui-tests:
    name: Run UI Tests (@ui)
    runs-on: ubuntu-latest
    needs: api-tests
    if: always()          

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Install Playwright CLI and browsers
        run: |
          dotnet tool install --global Microsoft.Playwright.CLI
          playwright install --with-deps

      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      - name: Download Allure results from API job
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: AllureResults-API
          path: ./AllureResults

      - name: Run SpecFlow UI tests
        run: >
          dotnet test --configuration Release
          --filter "TestCategory=ui"
          --no-build
          --logger "trx;LogFileName=ui_results.trx"
          --results-directory ./AllureResults
        env:
          HEADLESS: true
          ALLURE_SUITE: "UI Tests"
          ALLURE_EPIC: "NASA API Sign-Up Flow"

      - name: Generate combined Allure report (API + UI)
        run: allure generate ./AllureResults --clean -o ./AllureReport

      - name: Upload combined Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: AllureReport
          path: ./AllureReport

      - name: Upload raw Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: AllureResults
          path: ./AllureResults
