name: NASA Automation Tests

on:
  push:
    branches: [ main, development-branch ]
  pull_request:
    branches: [ main, development-branch ]

jobs:
  api-tests:
    name: Run API Tests (@api)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Run SpecFlow API tests
        run: dotnet test --configuration Release --filter "TestCategory=api" --no-build

  ui-tests:
    name: Run UI Tests (@ui)
    runs-on: ubuntu-latest
    needs: api-tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Run SpecFlow UI tests (headless)
        env:
          HEADLESS: true
        run: dotnet test --configuration Release --filter "TestCategory=ui" --no-build
